spring.application.name=tienda

#Se define el puerto por donde escucha el servidor web 
server.port=80


# se define el formato de de fecha de el servidor web
logging.pattern.dateformat=hh:mm

#se define no presentar el banner de SPRING en el log del servidor 
spring.main.banner-mode=off

#se evita el uso de cache en desarrollo en produccion si se debe usar 
spring.thymeleaf.cache=false
