spring.application.name=tienda
#Se define el puerto por donde escucha el servidor web 
server.port=80

# se define el formato de de fecha de el servidor web
logging.pattern.dateformat=hh:mm

#se define no presentar el banner de SPRING en el log del servidor 
spring.main.banner-mode=off

#se evita el uso de cache en desarrollo en produccion si se debe usar 
spring.thymeleaf.cache=false
#Conexión local a la BD Techshop en MySQL

spring.datasource.url=jdbc:mysql://localhost:3306/techshop
spring.datasource.url=jdbc:mysql://techshop-mcampos60001-camposariasmelannie-f91c.d.aivencloud.com:28202/techshop
 
#Usuario y clave de creaTablas.sql
spring.datasource.username=usuario_prueba
spring.datasource.password=Usuar1o_Clave.
 
#Driver y plataforma de comunicación
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect
 
#mostrar información en el log
spring.jpa.properties.hibernate.format_sql=true
logging.level.org.hibernate.SQL=DEBUG
logging.level.org.type.descriptor.sql.BasicBinder=TRACE